language: python
python:
  - "2.7"
#command to install dependencies
install: "pip install -r requirements.txt"
sudo: True
# command to run tests
script: nosetests

notifications:
    email:
        - david_gwartney@bmc.com
        - csm@bmc-2.flowdock.com
